import { getAuthUserId } from "@convex-dev/auth/server"
import { mutation, query } from "./_generated/server"
import { v } from "convex/values"
async function me(ctx:any){const u=await getAuthUserId(ctx);if(!u)return null;return ctx.db.query("creatorProfiles").withIndex("by_user",q=>q.eq("userId",u)).unique()}
export const getMine=query({args:{},returns:v.union(v.object({ _id:v.id("creatorProfiles"), _creationTime:v.number(), userId:v.id("users"), displayName:v.string(), bio:v.optional(v.string()), niche:v.optional(v.string()), status:v.union(v.literal("applicant"),v.literal("approved"),v.literal("suspended")), commissionBps:v.number(), totalClicks:v.number(), totalConversions:v.number(), totalRevenueMinor:v.number() }),v.null()),handler:async(ctx)=>me(ctx)})
export const apply=mutation({args:{displayName:v.string(),bio:v.optional(v.string()),niche:v.optional(v.string())},returns:v.union(v.object({ok:v.literal(true),id:v.id("creatorProfiles")}),v.object({ok:v.literal(false),message:v.string()})),handler:async(ctx,a)=>{const u=await getAuthUserId(ctx);if(!u)return{ok:false as const,message:"Sign in required."};const existing=await me(ctx);if(existing)return{ok:true as const,id:existing._id};if(a.displayName.trim().length<2)return{ok:false as const,message:"Display name is required."};const id=await ctx.db.insert("creatorProfiles",{userId:u,displayName:a.displayName.trim().slice(0,100),bio:a.bio?.trim().slice(0,1000),niche:a.niche?.trim().slice(0,100),status:"applicant",commissionBps:500,totalClicks:0,totalConversions:0,totalRevenueMinor:0});return{ok:true as const,id}}})
export const createCollection=mutation({args:{title:v.string(),description:v.optional(v.string()),coverImage:v.optional(v.string())},returns:v.union(v.id("creatorCollections"),v.null()),handler:async(ctx,a)=>{const c=await me(ctx);if(!c||c.status!=="approved")return null;const slug=a.title.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-")+"-"+Date.now().toString(36);return ctx.db.insert("creatorCollections",{creatorId:c._id,title:a.title.trim().slice(0,100),slug,description:a.description?.trim().slice(0,1000),coverImage:a.coverImage,status:"draft"})}})
export const addProduct=mutation({args:{collectionId:v.id("creatorCollections"),productId:v.id("products")},returns:v.boolean(),handler:async(ctx,a)=>{const c=await me(ctx);if(!c)return false;const col=await ctx.db.get(a.collectionId);if(!col||col.creatorId!==c._id)return false;const p=await ctx.db.get(a.productId);if(!p||p.status!=="active")return false;const existing=await ctx.db.query("creatorCollectionItems").withIndex("by_collection",q=>q.eq("collectionId",col._id)).filter(q=>q.eq(q.field("productId"),p._id)).first();if(existing)return true;const count=(await ctx.db.query("creatorCollectionItems").withIndex("by_collection",q=>q.eq("collectionId",col._id)).take(100)).length;await ctx.db.insert("creatorCollectionItems",{collectionId:col._id,productId:p._id,sortOrder:count});return true}})
export const publishCollection=mutation({args:{collectionId:v.id("creatorCollections")},returns:v.boolean(),handler:async(ctx,{collectionId})=>{const c=await me(ctx);if(!c)return false;const col=await ctx.db.get(collectionId);if(!col||col.creatorId!==c._id)return false;const items=await ctx.db.query("creatorCollectionItems").withIndex("by_collection",q=>q.eq("collectionId",collectionId)).take(100);if(!items.length)return false;await ctx.db.patch(col._id,{status:"published"});return true}})
export const storefront=query({args:{creatorId:v.id("creatorProfiles")},returns:v.array(v.any()),handler:async(ctx,{creatorId})=>{const cols=await ctx.db.query("creatorCollections").withIndex("by_creator",q=>q.eq("creatorId",creatorId)).filter(q=>q.eq(q.field("status"),"published")).take(50);const out:any[]=[];for(const c of cols){const items=await ctx.db.query("creatorCollectionItems").withIndex("by_collection",q=>q.eq("collectionId",c._id)).take(50);const products:any[]=[];for(const i of items){const p=await ctx.db.get(i.productId);if(p?.status==="active")products.push({id:p._id,name:p.name,slug:p.slug,priceMinor:p.priceMinor,currency:p.currency,image:p.images[0]??null})}out.push({...c,products})}return out}})
export const recordEvent=mutation({args:{creatorId:v.id("creatorProfiles"),collectionId:v.optional(v.id("creatorCollections")),productId:v.optional(v.id("products")),kind:v.union(v.literal("view"),v.literal("click"),v.literal("add_to_cart"),v.literal("purchase")),orderId:v.optional(v.id("orders")),valueMinor:v.optional(v.number())},returns:v.boolean(),handler:async(ctx,a)=>{const id=await ctx.db.insert("creatorEvents",{...a,createdAt:Date.now()});const c=await ctx.db.get(a.creatorId);if(c)await ctx.db.patch(c._id,{totalClicks:c.totalClicks+(a.kind==="click"?1:0),totalConversions:c.totalConversions+(a.kind==="purchase"?1:0),totalRevenueMinor:c.totalRevenueMinor+(a.kind==="purchase"?a.valueMinor??0:0)});return!!id}})
