import { v } from "convex/values"
import { action, mutation, query } from "./_generated/server"
import { getAuthUserId } from "@convex-dev/auth/server"
import { api } from "./_generated/api"
const rank=(t?:string)=>({obsidian:1,sovereign:2,sovereign_gilded:3,apex_imperial:4,sovereign_aethel:5}[t??"obsidian"]??1)
async function gate(ctx:any){const uid=await getAuthUserId(ctx);if(!uid)return null;const m=await ctx.db.query("membershipProfiles").withIndex("by_user",(q:any)=>q.eq("userId",uid)).unique();return rank(m?.tier)>=3?{uid,m}:null}
async function care(ctx:any,uid:any,type:string,ref?:string){await ctx.db.insert("vipCareQueue",{userId:uid,actionType:type,referenceId:ref,priority:300,status:"queued",createdAt:Date.now()})}
export const getPrivileges=query({args:{},returns:v.any(),handler:async ctx=>{const x=await gate(ctx);return x?{isGilded:true,tier:x.m.tier,pointsMultiplier:1.25,hideFromLimit:null,customization:true,auditing:true,guildCreation:true,guildAppointments:true,maxGuilds:3}:{isGilded:false}}})
export const createCustomization=mutation({args:{productId:v.id("products"),selections:v.any(),notes:v.optional(v.string()),brandEmail:v.optional(v.string()),customerEmail:v.string(),leadTimeEstimate:v.optional(v.string()),blueprint:v.optional(v.any())},returns:v.union(v.id("gildedCustomizations"),v.null()),handler:async(ctx,a)=>{const x=await gate(ctx);if(!x||!await ctx.db.get(a.productId))return null;const id=await ctx.db.insert("gildedCustomizations",{...a,userId:x.uid,status:"submitted",createdAt:Date.now(),updatedAt:Date.now()});await care(ctx,x.uid,"product_customization",String(id));return id}})
export const createAuditRun=mutation({args:{targetType:v.union(v.literal("homepage"),v.literal("profile")),targetId:v.optional(v.string()),configuration:v.any()},returns:v.union(v.id("gildedAuditRuns"),v.null()),handler:async(ctx,a)=>{const x=await gate(ctx);if(!x)return null;const id=await ctx.db.insert("gildedAuditRuns",{userId:x.uid,...a,findings:[{type:"layout",status:"captured"},{type:"accessibility",status:"review_required"},{type:"performance",status:"sandbox_ready"}],createdAt:Date.now()});await care(ctx,x.uid,"ecosystem_audit",String(id));return id}})
export const listMyCare=query({args:{},returns:v.array(v.any()),handler:async(ctx)=>{const uid=await getAuthUserId(ctx);return uid?await ctx.db.query("vipCareQueue").withIndex("by_user_created",q=>q.eq("userId",uid)).order("desc").take(50):[]}})
export const createGuild=mutation({args:{name:v.string(),slug:v.string(),territory:v.string(),description:v.optional(v.string())},returns:v.union(v.id("gildedGuilds"),v.null()),handler:async(ctx,a)=>{const x=await gate(ctx);if(!x)return null;const owned=await ctx.db.query("gildedGuilds").withIndex("by_owner",q=>q.eq("ownerId",x.uid)).collect();if(owned.length>=3)return null;const id=await ctx.db.insert("gildedGuilds",{...a,ownerId:x.uid,status:"active",createdAt:Date.now()});await ctx.db.insert("gildedTerritoryPolicies",{guildId:id,territory:a.territory,policy:{mode:"owner_governed",appointments:true},updatedAt:Date.now(),updatedBy:x.uid});return id}})
export const listMyGuilds=query({args:{},returns:v.any(),handler:async(ctx)=>{const uid=await getAuthUserId(ctx);if(!uid)return {owned:[],memberships:[]};return {owned:await ctx.db.query("gildedGuilds").withIndex("by_owner",q=>q.eq("ownerId",uid)).collect(),memberships:await ctx.db.query("gildedGuildMembers").withIndex("by_user",q=>q.eq("userId",uid)).collect()}}})
export const appointGuildRole=mutation({args:{guildId:v.id("gildedGuilds"),userId:v.id("users"),role:v.union(v.literal("member"),v.literal("warden"),v.literal("steward"))},returns:v.boolean(),handler:async(ctx,a)=>{const x=await gate(ctx),g=x&&await ctx.db.get(a.guildId);if(!x||!g||g.ownerId!==x.uid||g.status!=="active")return false;const e=await ctx.db.query("gildedGuildMembers").withIndex("by_guild_user",q=>q.eq("guildId",a.guildId).eq("userId",a.userId)).unique();if(e)await ctx.db.patch(e._id,{role:a.role,status:"active",appointedBy:x.uid,appointedAt:Date.now()});else await ctx.db.insert("gildedGuildMembers",{guildId:a.guildId,userId:a.userId,role:a.role,status:"active",appointedBy:x.uid,appointedAt:Date.now()});return true}})
export const setTerritoryPolicy=mutation({args:{guildId:v.id("gildedGuilds"),policy:v.any()},returns:v.boolean(),handler:async(ctx,a)=>{const x=await gate(ctx),g=x&&await ctx.db.get(a.guildId);if(!x||!g||g.ownerId!==x.uid)return false;const p=await ctx.db.query("gildedTerritoryPolicies").withIndex("by_guild",q=>q.eq("guildId",a.guildId)).unique();if(p)await ctx.db.patch(p._id,{policy:a.policy,updatedAt:Date.now(),updatedBy:x.uid});return true}})
export const getCustomization=query({args:{customizationId:v.id("gildedCustomizations")},returns:v.union(v.any(),v.null()),handler:async(ctx,a)=>{const x=await gate(ctx),c=await ctx.db.get(a.customizationId);if(!x||!c||c.userId!==x.uid)return null;return {c,recipients:[...(c.brandEmail?[{type:"brand",email:c.brandEmail}]:[]),{type:"customer",email:c.customerEmail}]}}})
export const recordDispatch=mutation({args:{customizationId:v.id("gildedCustomizations"),recipientType:v.union(v.literal("brand"),v.literal("customer")),recipientEmail:v.string(),subject:v.string(),status:v.union(v.literal("queued"),v.literal("sent"),v.literal("failed"))},returns:v.id("gildedDispatches"),handler:async(ctx,a)=>ctx.db.insert("gildedDispatches",{...a,createdAt:Date.now()})})
export const dispatchCustomizationEmails=action({args:{customizationId:v.id("gildedCustomizations")},returns:v.any(),handler:async(ctx,a)=>{const c=await ctx.runQuery(api.gilded.getCustomization,a);if(!c)return {ok:false,code:"NOT_FOUND"};const endpoint=process.env.EMAIL_NOTIFICATION_ENDPOINT;if(!endpoint)return {ok:false,code:"EMAIL_NOT_CONFIGURED"};for(const r of c.recipients){const res=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({toEmail:r.email,subject:"EVARA-LUX Sovereign-Gilded Product Specification",message:JSON.stringify(c.c),chatId:process.env.CHAT_ID,appName:process.env.APP_NAME,secretKey:process.env.SECRET_KEY})});if(!res.ok)return {ok:false,code:"EMAIL_FAILED"}}return {ok:true}}})
