import { getAuthUserId } from "@convex-dev/auth/server"
import { mutation, query } from "./_generated/server"
import { v } from "convex/values"
const R=v.union(v.literal("spam"),v.literal("scam"),v.literal("harassment"),v.literal("hate"),v.literal("sexual"),v.literal("copyright"),v.literal("impersonation"),v.literal("other"))
const T=v.union(v.literal("feed_item"),v.literal("comment"),v.literal("profile"),v.literal("message"),v.literal("product"),v.literal("creator"))
async function admin(ctx:any,u:any){const p=await ctx.db.query("userProfiles").withIndex("by_user",q=>q.eq("userId",u)).unique();return p?.role==="admin"}
export const report=mutation({args:{targetType:T,targetId:v.string(),reason:R,details:v.optional(v.string())},returns:v.union(v.object({ok:v.literal(true),id:v.id("reports")}),v.object({ok:v.literal(false),message:v.string()})),handler:async(ctx,a)=>{const u=await getAuthUserId(ctx);if(!u)return{ok:false as const,message:"Sign in required."};if(a.details&&a.details.length>2000)return{ok:false as const,message:"Report details are too long."};return{ok:true as const,id:await ctx.db.insert("reports",{...a,reporterId:u,status:"open"})}}})
export const queue=query({args:{limit:v.optional(v.number())},returns:v.array(v.any()),handler:async(ctx,{limit})=>{const u=await getAuthUserId(ctx);if(!u||!(await admin(ctx,u)))return[];return ctx.db.query("reports").withIndex("by_status",q=>q.eq("status","open")).order("desc").take(Math.min(Math.max(limit??50,1),100))}})
export const resolve=mutation({args:{reportId:v.id("reports"),action:v.union(v.literal("warn"),v.literal("hide"),v.literal("restore"),v.literal("suspend"),v.literal("delete")),resolution:v.string()},returns:v.boolean(),handler:async(ctx,a)=>{const u=await getAuthUserId(ctx);if(!u||!(await admin(ctx,u)))return false;const r=await ctx.db.get(a.reportId);if(!r)return false;await ctx.db.patch(r._id,{status:"resolved",resolution:a.resolution});await ctx.db.insert("moderationActions",{adminId:u,reportId:r._id,targetType:r.targetType,targetId:r.targetId,action:a.action,reason:a.resolution});if(r.targetType==="feed_item"&&(a.action==="hide"||a.action==="delete")){const item=await ctx.db.get(r.targetId as any);if(item)await ctx.db.patch(item._id,{status:a.action==="hide"?"hidden":"deleted"})}return true}})
