import { getAuthUserId } from "@convex-dev/auth/server"
import { internalAction, internalMutation, internalQuery, mutation, query } from "./_generated/server"
import { internal } from "./_generated/api"
import { v } from "convex/values"
const pref=v.object({orders:v.boolean(),payments:v.boolean(),social:v.boolean(),promotions:v.boolean(),creator:v.boolean(),support:v.boolean(),security:v.boolean(),email:v.boolean(),push:v.boolean(),updatedAt:v.number()})
export const getPreferences=query({args:{},returns:v.union(pref,v.null()),handler:async(ctx)=>{const u=await getAuthUserId(ctx);if(!u)return null;const x=await ctx.db.query("notificationPreferences").withIndex("by_user",q=>q.eq("userId",u)).unique();return x?{...x}: {orders:true,payments:true,social:true,promotions:true,creator:true,support:true,security:true,email:false,push:true,updatedAt:Date.now()}}})
export const updatePreferences=mutation({args:{orders:v.boolean(),payments:v.boolean(),social:v.boolean(),promotions:v.boolean(),creator:v.boolean(),support:v.boolean(),security:v.boolean(),email:v.boolean(),push:v.boolean()},returns:v.boolean(),handler:async(ctx,a)=>{const u=await getAuthUserId(ctx);if(!u)return false;const x=await ctx.db.query("notificationPreferences").withIndex("by_user",q=>q.eq("userId",u)).unique();if(x)await ctx.db.patch(x._id,{...a,updatedAt:Date.now()});else await ctx.db.insert("notificationPreferences",{userId:u,...a,updatedAt:Date.now()});return true}})
// Unsubscribe-by-link: called from the "unsubscribe" link appended to
// promotional emails (see deliver, below). No auth required — the link
// itself, containing this user's id, is the credential, exactly like every
// standard email unsubscribe link. Only ever turns promotions off; never
// touches order/payment/security notifications, which aren't marketing.
export const unsubscribePromotions=mutation({args:{userId:v.id("users")},returns:v.boolean(),handler:async(ctx,{userId})=>{const x=await ctx.db.query("notificationPreferences").withIndex("by_user",q=>q.eq("userId",userId)).unique();if(x)await ctx.db.patch(x._id,{promotions:false,updatedAt:Date.now()});else await ctx.db.insert("notificationPreferences",{userId,orders:true,payments:true,social:true,promotions:false,creator:true,support:true,security:true,email:false,push:true,updatedAt:Date.now()});return true}})
export const listMine=query({args:{limit:v.optional(v.number())},returns:v.array(v.any()),handler:async(ctx,{limit})=>{const u=await getAuthUserId(ctx);if(!u)return[];return ctx.db.query("notifications").withIndex("by_user_created",q=>q.eq("userId",u)).order("desc").take(Math.min(Math.max(limit??30,1),100))}})
export const unreadCount=query({args:{},returns:v.number(),handler:async(ctx)=>{const u=await getAuthUserId(ctx);if(!u)return 0;return(await ctx.db.query("notifications").withIndex("by_user_created",q=>q.eq("userId",u)).order("desc").take(100)).filter(n=>n.readAt===undefined).length}})
export const markRead=mutation({args:{notificationId:v.id("notifications")},returns:v.boolean(),handler:async(ctx,{notificationId})=>{const u=await getAuthUserId(ctx);if(!u)return false;const n=await ctx.db.get(notificationId);if(!n||n.userId!==u)return false;if(n.readAt===undefined)await ctx.db.patch(n._id,{readAt:Date.now()});return true}})
export const markAllRead=mutation({args:{},returns:v.number(),handler:async(ctx)=>{const u=await getAuthUserId(ctx);if(!u)return 0;const rows=(await ctx.db.query("notifications").withIndex("by_user_created",q=>q.eq("userId",u)).order("desc").take(100)).filter(n=>n.readAt===undefined);for(const n of rows)await ctx.db.patch(n._id,{readAt:Date.now()});return rows.length}})
export const getDeliveryContext=internalQuery({args:{userId:v.id("users")},returns:v.object({email:v.union(v.string(),v.null()),phone:v.union(v.string(),v.null()),emailEnabled:v.boolean(),pushEnabled:v.boolean(),phoneVerified:v.boolean()}),handler:async(ctx,{userId})=>{const user=await ctx.db.get(userId);const p=await ctx.db.query("userProfiles").withIndex("by_user",q=>q.eq("userId",userId)).unique();const prefs=await ctx.db.query("notificationPreferences").withIndex("by_user",q=>q.eq("userId",userId)).unique();const kindEnabled=(kind:string)=>prefs?Boolean((prefs as any)[kind==="promotion"?"promotions":kind]??true):true;return{email:(user as any)?.email??null,phone:p?.phone??null,emailEnabled:kindEnabled("system")&&(prefs?.email??false),pushEnabled:prefs?.push??true,phoneVerified:p?.phone!==undefined&&p?.verificationStatus==="verified"}}})

export const deliver=internalAction({args:{userId:v.id("users"),kind:v.union(v.literal("order"),v.literal("payment"),v.literal("social"),v.literal("security"),v.literal("promotion"),v.literal("system"),v.literal("creator"),v.literal("support")),title:v.string(),body:v.string(),actionUrl:v.optional(v.string())},returns:v.object({email:v.boolean(),sms:v.boolean()}),handler:async(ctx,a)=>{const c=await ctx.runQuery(internal.notifications.getDeliveryContext,{userId:a.userId});let email=false;let sms=false;const emailEndpoint=process.env.EMAIL_NOTIFICATION_ENDPOINT;const smsEndpoint=process.env.SMS_NOTIFICATION_ENDPOINT;
  // Promotional emails get an unsubscribe link appended to the body and a
  // manage-preferences link as the action URL, so the required opt-out is
  // in the email itself, not only in account settings the recipient has to
  // go find. Transactional mail (order/payment/security/support) isn't
  // marketing and keeps its own actionUrl untouched.
  const isPromotional=a.kind==="promotion"
  const appUrl=process.env.APP_URL??"https://evara-lux.app"
  const unsubscribeUrl=isPromotional?`${appUrl}/unsubscribe?u=${a.userId}`:undefined
  const deliveredBody=isPromotional?`${a.body}\n\nManage or unsubscribe from promotional emails: ${unsubscribeUrl}`:a.body
  const deliveredActionUrl=isPromotional?(a.actionUrl??`${appUrl}/settings`):a.actionUrl
  if(c.email&&c.emailEnabled&&emailEndpoint){const r=await fetch(emailEndpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:c.email,subject:a.title,body:deliveredBody,actionUrl:deliveredActionUrl,unsubscribeUrl,appName:process.env.APP_NAME??"EVARA-LUX",secretKey:process.env.EMAIL_NOTIFICATION_SECRET_KEY})});email=r.ok}if(c.phone&&c.phoneVerified&&smsEndpoint&&["security","order","payment","support"].includes(a.kind)){const r=await fetch(smsEndpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phone:c.phone,title:a.title,message:a.body,appName:process.env.APP_NAME??"EVARA-LUX",secretKey:process.env.SMS_NOTIFICATION_SECRET_KEY})});sms=r.ok}return{email,sms}}})

export const createInternal=internalMutation({args:{userId:v.id("users"),kind:v.union(v.literal("order"),v.literal("payment"),v.literal("social"),v.literal("security"),v.literal("promotion"),v.literal("system"),v.literal("creator"),v.literal("support")),title:v.string(),body:v.string(),actionUrl:v.optional(v.string()),priority:v.union(v.literal("low"),v.literal("normal"),v.literal("high"))},returns:v.id("notifications"),handler:async(ctx,a)=>{const id=await ctx.db.insert("notifications",{...a,createdAt:Date.now()});await ctx.scheduler.runAfter(0,internal.notifications.deliver,{userId:a.userId,kind:a.kind,title:a.title,body:a.body,actionUrl:a.actionUrl});return id}})
