import { mutation, query } from "./_generated/server"
import { v } from "convex/values"

async function sha(value:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("")}
function token(){const a=new Uint8Array(32);crypto.getRandomValues(a);return btoa(String.fromCharCode(...a)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=/g,"")}
function answerNorm(x:string){return x.trim().toLowerCase().replace(/\s+/g," ")}

export const start=mutation({args:{identifierRaw:v.string()},returns:v.object({ok:v.boolean(),challenge:v.optional(v.string()),questions:v.optional(v.array(v.object({id:v.string(),prompt:v.string()}))),message:v.string()}),handler:async(ctx,{identifierRaw})=>{const identifier=identifierRaw.trim().replace(/^@/,"").toLowerCase();let p=await ctx.db.query("userProfiles").withIndex("by_username_lower",q=>q.eq("usernameLower",identifier)).unique();let user=p?await ctx.db.get(p.userId):await ctx.db.query("users").withIndex("email",q=>q.eq("email",identifier)).unique();if(!user?.email)return{ok:false,message:"We couldn't find that EVARA account."};if(!p)p=await ctx.db.query("userProfiles").withIndex("by_user",q=>q.eq("userId",user._id)).unique();if(!p)return{ok:false,message:"Account profile is incomplete."};const questions=[{id:"username",prompt:"What is your EVARA username?"},{id:"publicId",prompt:"What is your EVARA-LUX member ID?"},{id:"phoneLast4",prompt:"What are the last 4 digits of your verified phone number?"}];const answers=[p.usernameLower??p.username??"",p.publicId??"",p.phone?p.phone.replace(/\D/g,"").slice(-4):""];const challenge=token();await ctx.db.insert("accountRecovery",{userId:user._id,email:user.email,challengeHash:await sha(challenge),questions:await Promise.all(questions.map(async(q,i)=>({id:q.id,prompt:q.prompt,answerHash:await sha(answerNorm(answers[i]))}))),attempts:0,expiresAt:Date.now()+15*60_000});return{ok:true,challenge,questions,message:"Answer these account questions before a password reset can be issued."}}})

export const verify=mutation({args:{challenge:v.string(),answers:v.array(v.object({id:v.string(),answer:v.string()}))},returns:v.object({ok:v.boolean(),recoveryToken:v.optional(v.string()),email:v.optional(v.string()),message:v.string()}),handler:async(ctx,{challenge,answers})=>{const h=await sha(challenge);const row=await ctx.db.query("accountRecovery").withIndex("by_challenge",q=>q.eq("challengeHash",h)).unique();if(!row||row.challengeHash!==h||row.expiresAt<Date.now())return{ok:false,message:"Recovery session expired. Start again."};if(row.attempts>=3)return{ok:false,message:"Too many attempts. Start recovery again."};let ok=true;for(const q of row.questions){const a=answers.find(x=>x.id===q.id);if(!a||await sha(answerNorm(a.answer))!==q.answerHash)ok=false}if(!ok){await ctx.db.patch(row._id,{attempts:row.attempts+1});return{ok:false,message:"One or more answers did not match our account records."}}const recoveryToken=token();await ctx.db.patch(row._id,{verifiedAt:Date.now(),challengeHash:await sha(recoveryToken)});return{ok:true,recoveryToken,email:row.email,message:"Identity verified. You may now request a password reset code."}}})
