import { getAuthUserId } from "@convex-dev/auth/server"
import { mutation, query } from "./_generated/server"
import { v } from "convex/values"
import { internal } from "./_generated/api"
const C=v.union(v.literal("order"),v.literal("payment"),v.literal("account"),v.literal("product"),v.literal("social"),v.literal("other"))
export const listMine=query({args:{},returns:v.array(v.any()),handler:async(ctx)=>{const u=await getAuthUserId(ctx);if(!u)return[];return ctx.db.query("supportTickets").withIndex("by_user",q=>q.eq("userId",u)).order("desc").take(50)}})
export const getTicket=query({args:{ticketId:v.id("supportTickets")},returns:v.union(v.object({ticket:v.object({_id:v.id("supportTickets"),_creationTime:v.number(),userId:v.id("users"),subject:v.string(),category:v.union(v.literal("order"),v.literal("payment"),v.literal("account"),v.literal("product"),v.literal("social"),v.literal("other")),status:v.union(v.literal("open"),v.literal("pending"),v.literal("resolved"),v.literal("closed")),priority:v.union(v.literal("low"),v.literal("normal"),v.literal("high"),v.literal("urgent")),orderId:v.optional(v.id("orders")),lastMessageAt:v.number()}),messages:v.array(v.object({_id:v.id("supportMessages"),_creationTime:v.number(),ticketId:v.id("supportTickets"),senderId:v.id("users"),role:v.union(v.literal("customer"),v.literal("agent"),v.literal("ai")),body:v.string(),createdAt:v.number()}))}),v.null()),handler:async(ctx,{ticketId})=>{const u=await getAuthUserId(ctx);if(!u)return null;const t=await ctx.db.get(ticketId);if(!t||t.userId!==u)return null;const messages=await ctx.db.query("supportMessages").withIndex("by_ticket_time",q=>q.eq("ticketId",ticketId)).order("asc").take(200);return{ticket:t,messages}}})
export const createTicket=mutation({args:{subject:v.string(),category:C,body:v.string(),orderId:v.optional(v.id("orders"))},returns:v.union(v.object({ok:v.literal(true),id:v.id("supportTickets")}),v.object({ok:v.literal(false),message:v.string()})),handler:async(ctx,a)=>{const u=await getAuthUserId(ctx);if(!u)return{ok:false as const,message:"Sign in required."};if(a.subject.trim().length<3||a.body.trim().length<3)return{ok:false as const,message:"Please provide a useful subject and message."};if(a.orderId){const o=await ctx.db.get(a.orderId);if(!o||o.userId!==u)return{ok:false as const,message:"That order is not yours."}}const now=Date.now();const id=await ctx.db.insert("supportTickets",{userId:u,subject:a.subject.trim().slice(0,200),category:a.category,status:"open",priority:"normal",orderId:a.orderId,lastMessageAt:now});await ctx.db.insert("supportMessages",{ticketId:id,senderId:u,role:"customer",body:a.body.trim().slice(0,5000),createdAt:now});await ctx.scheduler.runAfter(0,internal.notifications.createInternal,{userId:u,kind:"support",title:"Support request received",body:"Your EVARA support request is now in the queue.",actionUrl:"/account",priority:"normal"});return{ok:true as const,id}}})
export const reply=mutation({args:{ticketId:v.id("supportTickets"),body:v.string()},returns:v.boolean(),handler:async(ctx,{ticketId,body})=>{const u=await getAuthUserId(ctx);if(!u||!body.trim())return false;const t=await ctx.db.get(ticketId);if(!t||t.userId!==u||t.status==="closed")return false;await ctx.db.insert("supportMessages",{ticketId,senderId:u,role:"customer",body:body.trim().slice(0,5000),createdAt:Date.now()});await ctx.db.patch(t._id,{status:"open",lastMessageAt:Date.now()});return true}})
export const adminReply=mutation({args:{ticketId:v.id("supportTickets"),body:v.string(),status:v.union(v.literal("open"),v.literal("pending"),v.literal("resolved"),v.literal("closed"))},returns:v.boolean(),handler:async(ctx,a)=>{const u=await getAuthUserId(ctx);if(!u||!a.body.trim())return false;const p=await ctx.db.query("userProfiles").withIndex("by_user",q=>q.eq("userId",u)).unique();if(p?.role!=="admin")return false;const t=await ctx.db.get(a.ticketId);if(!t)return false;await ctx.db.insert("supportMessages",{ticketId:t._id,senderId:u,role:"agent",body:a.body.trim().slice(0,5000),createdAt:Date.now()});await ctx.db.patch(t._id,{status:a.status,lastMessageAt:Date.now()});await ctx.scheduler.runAfter(0,internal.notifications.createInternal,{userId:t.userId,kind:"support",title:"EVARA support replied",body:a.body.trim().slice(0,240),actionUrl:"/account",priority:"normal"});return true}})
export const adminQueue=query({args:{},returns:v.array(v.any()),handler:async(ctx)=>{const u=await getAuthUserId(ctx);if(!u)return[];const p=await ctx.db.query("userProfiles").withIndex("by_user",q=>q.eq("userId",u)).unique();if(p?.role!=="admin")return[];return ctx.db.query("supportTickets").withIndex("by_status_priority",q=>q.eq("status","open")).order("desc").take(100)}})
