import { useState } from "react"
import { useMutation, useQuery } from "convex/react"
import { ShieldCheck, Crown, Users, Map, Sparkles, Mail, LayoutDashboard } from "lucide-react"
import { api } from "../../../convex/_generated/api"

export function GildedConsole(){
 const p=useQuery(api.gilded.getPrivileges), guilds=useQuery(api.gilded.listMyGuilds)
 const createGuild=useMutation(api.gilded.createGuild), appoint=useMutation(api.gilded.appointGuildRole), audit=useMutation(api.gilded.createAuditRun)
 const [name,setName]=useState(""),[territory,setTerritory]=useState(""),[target,setTarget]=useState(""),[guildId,setGuildId]=useState<any>(null),[userId,setUserId]=useState<any>(null),[role,setRole]=useState<"member"|"warden"|"steward">("steward"),[notice,setNotice]=useState("")
 if(!p?.isGilded || !guilds)return null
 const flash=(s:string)=>{setNotice(s);setTimeout(()=>setNotice(""),2500)}
 return <section className="mt-5 overflow-hidden border border-yellow-500/35 bg-gradient-to-br from-yellow-500/10 via-background to-yellow-300/5 p-6 shadow-2xl shadow-yellow-950/20 md:p-8">
  <div className="flex flex-col gap-5 lg:flex-row lg:justify-between"><div><p className="text-[10px] uppercase tracking-[.3em] text-yellow-300">EVARA·LUX / SOVEREIGN-GILDED</p><h2 className="mt-2 font-display text-3xl">The Elite layer.</h2><p className="mt-2 max-w-2xl text-xs leading-6 text-muted-foreground">Liquid-gold identity, white-glove routing, ecosystem audit controls and territorial guild governance.</p></div><Crown className="h-8 w-8 text-yellow-300"/></div>
  <div className="mt-7 grid gap-3 md:grid-cols-4">{[["Nexa podium","1.25×"],["Privacy","Uncapped"],["Concierge","Priority 300"],["Guilds","Up to 3"]].map(([a,b])=><div className="border border-yellow-500/20 p-4" key={a}><p className="text-[9px] uppercase tracking-[.15em] text-muted-foreground">{a}</p><p className="mt-2 text-sm text-yellow-100">{b}</p></div>)}</div>
  <div className="mt-7 grid gap-5 lg:grid-cols-2">
   <div className="border border-yellow-500/20 p-5"><div className="flex items-center gap-2"><LayoutDashboard className="h-4 w-4 text-yellow-300"/><span className="text-[10px] uppercase tracking-[.18em]">Ecosystem audit</span></div><p className="mt-2 text-xs text-muted-foreground">Capture a sandbox audit configuration for homepage or profile stress-testing.</p><button onClick={async()=>{const id=await audit({targetType:"homepage",configuration:{mode:"gilded-sandbox",checks:["layout","accessibility","performance"]}});flash(id?"Audit run captured":"Audit unavailable")}} className="mt-4 border border-yellow-400/40 px-4 py-2 text-[9px] uppercase tracking-[.14em]">Run homepage audit</button></div>
   <div className="border border-yellow-500/20 p-5"><div className="flex items-center gap-2"><Mail className="h-4 w-4 text-yellow-300"/><span className="text-[10px] uppercase tracking-[.18em]">Product specification</span></div><p className="mt-2 text-xs text-muted-foreground">The backend accepts structured material, dimension, engraving and palette specifications and can dispatch them to brand + customer once email configuration is active.</p><div className="mt-3 flex items-center gap-2 text-[9px] text-muted-foreground"><ShieldCheck className="h-3 w-3"/> Server-gated to Gilded</div></div>
  </div>
  <div className="mt-5 border border-yellow-500/20 p-5"><div className="flex items-center gap-2"><Users className="h-4 w-4 text-yellow-300"/><span className="text-[10px] uppercase tracking-[.18em]">Guild & territory command</span></div><p className="mt-2 text-xs text-muted-foreground">Create a guild, establish its territory, then appoint members as Steward, Warden or Member. Appointments are owner-authorized on the server.</p>
   <div className="mt-4 grid gap-2 md:grid-cols-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Guild name" className="border border-border bg-background px-3 py-2 text-xs"/><input value={territory} onChange={e=>setTerritory(e.target.value)} placeholder="Territory" className="border border-border bg-background px-3 py-2 text-xs"/><button onClick={async()=>{const id=await createGuild({name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,"-"),territory});setGuildId(id);flash(id?"Guild founded":"Guild limit reached")}} className="border border-yellow-400/40 px-3 py-2 text-[9px] uppercase tracking-[.14em]">Found guild</button></div>
   <div className="mt-4 grid gap-2 md:grid-cols-3"><input value={target} onChange={e=>setTarget(e.target.value)} placeholder="User ID to appoint" className="border border-border bg-background px-3 py-2 text-xs"/><select value={role} onChange={e=>setRole(e.target.value as any)} className="border border-border bg-background px-3 py-2 text-xs"><option value="steward">Steward</option><option value="warden">Warden</option><option value="member">Member</option></select><button disabled={!guildId||!target} onClick={async()=>{const ok=await appoint({guildId,userId:target as any,role});flash(ok?"Appointment recorded":"Appointment denied")}} className="border border-yellow-400/40 px-3 py-2 text-[9px] uppercase tracking-[.14em]">Appoint</button></div>
   {guilds?.owned?.length>0&&<p className="mt-3 text-[10px] text-muted-foreground"><Map className="mr-1 inline h-3 w-3"/> {guilds.owned.length} guild territory record(s) under your command.</p>}
  </div>
  {notice&&<p className="mt-4 text-[10px] text-yellow-200">{notice}</p>}
 </section>
}
